CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'USER',
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_email_normalized
        CHECK (email = LOWER(BTRIM(email))),
    CONSTRAINT ck_users_display_name_not_blank
        CHECK (LENGTH(BTRIM(display_name)) > 0),
    CONSTRAINT ck_users_role
        CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_users_status
        CHECK (status IN ('ACTIVE', 'LOCKED', 'DISABLED')),
    CONSTRAINT ck_users_version_non_negative
        CHECK (version >= 0)
);

COMMENT ON TABLE users IS 'ユーザー情報';
COMMENT ON COLUMN users.email IS '正規化済みメールアドレス';
COMMENT ON COLUMN users.password_hash IS 'ハッシュ化済みパスワード';

GRANT USAGE ON SCHEMA public TO user_management_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE users TO user_management_app;
GRANT USAGE, SELECT ON SEQUENCE users_id_seq TO user_management_app;
